#data cleaning

In [113]:
import pandas as pd
import numpy as np

In [114]:
df = pd.read_csv('Dataset.csv')
df

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
0,01-01-2016 21:11,01-01-2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,01-02-2016 01:25,01-02-2016 01:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,01-02-2016 20:25,01-02-2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,01-05-2016 17:31,01-05-2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,01-06-2016 14:42,01-06-2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
...,...,...,...,...,...,...,...
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [115]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   START_DATE  1156 non-null   str
 1   END_DATE    1155 non-null   str
 2   CATEGORY    1155 non-null   str
 3   START       1155 non-null   str
 4   STOP        1155 non-null   str
 5   MILES       1156 non-null   float64
 6   PURPOSE     653 non-null    str
dtypes: float64(1), str(6)
memory usage: 63.3 KB

In [116]:
# #must not do
# # it will chnage the last row to 0.0
# # but tht indicates actual total 
# df.isnull().sum()
# df.fillna()

In [117]:
df.describe()

              MILES
count   1156.000000
mean      21.115398
std      359.299007
min        0.500000
25%        2.900000
50%        6.000000
75%       10.400000
max    12204.700000

In [118]:
# insight = most of the rides travel 10 miles

In [119]:
# df.drop(1155)

In [120]:
df['start'] = pd.to_datetime(df['START_DATE'] , format= 'mixed' , errors='coerce')
df['end'] = pd.to_datetime(df['END_DATE'], format='mixed', errors='coerce')
# new_df = df[['start', 'end']] #changes to new_df will lead chnages to acual df as well
new_df = df[['start', 'end']].copy() #changes to new_df will not lead chnages to acual df as well
new_df['start_date'] = df['start'].dt.date
new_df['start_time'] = df['start'].dt.time
new_df['end_date'] = df['end'].dt.date
new_df['end_time'] = df['end'].dt.time
new_df

,start,end,start_date,start_time,end_date,end_time
0,2016-01-01 21:11:00,2016-01-01 21:17:00,2016-01-01,21:11:00,2016-01-01,21:17:00
1,2016-01-02 01:25:00,2016-01-02 01:37:00,2016-01-02,01:25:00,2016-01-02,01:37:00
2,2016-01-02 20:25:00,2016-01-02 20:38:00,2016-01-02,20:25:00,2016-01-02,20:38:00
3,2016-01-05 17:31:00,2016-01-05 17:45:00,2016-01-05,17:31:00,2016-01-05,17:45:00
4,2016-01-06 14:42:00,2016-01-06 15:49:00,2016-01-06,14:42:00,2016-01-06,15:49:00
...,...,...,...,...,...,...
1151,2016-12-31 13:24:00,2016-12-31 13:42:00,2016-12-31,13:24:00,2016-12-31,13:42:00
1152,2016-12-31 15:03:00,2016-12-31 15:38:00,2016-12-31,15:03:00,2016-12-31,15:38:00
1153,2016-12-31 21:32:00,2016-12-31 21:50:00,2016-12-31,21:32:00,2016-12-31,21:50:00
1154,2016-12-31 22:08:00,2016-12-31 23:51:00,2016-12-31,22:08:00,2016-12-31,23:51:00
1155,NaT,NaT,NaT,NaT,NaT,NaT

In [121]:
new_df['duration'] = new_df['end'] - new_df['start']
new_df 
# ACTUAL DATETIME HI SUBTRACT KR SKTE HAI
# CONVERTED NAI KR SKTE HAI

,start,end,start_date,start_time,end_date,end_time,duration
0,2016-01-01 21:11:00,2016-01-01 21:17:00,2016-01-01,21:11:00,2016-01-01,21:17:00,0 days 00:06:00
1,2016-01-02 01:25:00,2016-01-02 01:37:00,2016-01-02,01:25:00,2016-01-02,01:37:00,0 days 00:12:00
2,2016-01-02 20:25:00,2016-01-02 20:38:00,2016-01-02,20:25:00,2016-01-02,20:38:00,0 days 00:13:00
3,2016-01-05 17:31:00,2016-01-05 17:45:00,2016-01-05,17:31:00,2016-01-05,17:45:00,0 days 00:14:00
4,2016-01-06 14:42:00,2016-01-06 15:49:00,2016-01-06,14:42:00,2016-01-06,15:49:00,0 days 01:07:00
...,...,...,...,...,...,...,...
1151,2016-12-31 13:24:00,2016-12-31 13:42:00,2016-12-31,13:24:00,2016-12-31,13:42:00,0 days 00:18:00
1152,2016-12-31 15:03:00,2016-12-31 15:38:00,2016-12-31,15:03:00,2016-12-31,15:38:00,0 days 00:35:00
1153,2016-12-31 21:32:00,2016-12-31 21:50:00,2016-12-31,21:32:00,2016-12-31,21:50:00,0 days 00:18:00
1154,2016-12-31 22:08:00,2016-12-31 23:51:00,2016-12-31,22:08:00,2016-12-31,23:51:00,0 days 01:43:00
1155,NaT,NaT,NaT,NaT,NaT,NaT,NaT

In [122]:
new_df['miles'] = df['MILES']
new_df['category'] = df['CATEGORY']
new_df['purpose'] = df['PURPOSE']
new_df['start'] = df['START']
new_df['end'] = df['STOP']
new_df

,start,end,start_date,start_time,end_date,end_time,duration,miles,category,purpose
0,Fort Pierce,Fort Pierce,2016-01-01,21:11:00,2016-01-01,21:17:00,0 days 00:06:00,5.1,Business,Meal/Entertain
1,Fort Pierce,Fort Pierce,2016-01-02,01:25:00,2016-01-02,01:37:00,0 days 00:12:00,5.0,Business,NaN
2,Fort Pierce,Fort Pierce,2016-01-02,20:25:00,2016-01-02,20:38:00,0 days 00:13:00,4.8,Business,Errand/Supplies
3,Fort Pierce,Fort Pierce,2016-01-05,17:31:00,2016-01-05,17:45:00,0 days 00:14:00,4.7,Business,Meeting
4,Fort Pierce,West Palm Beach,2016-01-06,14:42:00,2016-01-06,15:49:00,0 days 01:07:00,63.7,Business,Customer Visit
...,...,...,...,...,...,...,...,...,...,...
1151,Kar?chi,Unknown Location,2016-12-31,13:24:00,2016-12-31,13:42:00,0 days 00:18:00,3.9,Business,Temporary Site
1152,Unknown Location,Unknown Location,2016-12-31,15:03:00,2016-12-31,15:38:00,0 days 00:35:00,16.2,Business,Meeting
1153,Katunayake,Gampaha,2016-12-31,21:32:00,2016-12-31,21:50:00,0 days 00:18:00,6.4,Business,Temporary Site
1154,Gampaha,Ilukwatta,2016-12-31,22:08:00,2016-12-31,23:51:00,0 days 01:43:00,48.2,Business,Temporary Site
1155,NaN,NaN,NaT,NaT,NaT,NaT,NaT,12204.7,NaN,NaN

In [123]:
new_df['duration_minutes'] = new_df['duration'].dt.total_seconds() / 60
new_df

,start,end,start_date,start_time,end_date,end_time,duration,miles,category,purpose,duration_minutes
0,Fort Pierce,Fort Pierce,2016-01-01,21:11:00,2016-01-01,21:17:00,0 days 00:06:00,5.1,Business,Meal/Entertain,6.0
1,Fort Pierce,Fort Pierce,2016-01-02,01:25:00,2016-01-02,01:37:00,0 days 00:12:00,5.0,Business,NaN,12.0
2,Fort Pierce,Fort Pierce,2016-01-02,20:25:00,2016-01-02,20:38:00,0 days 00:13:00,4.8,Business,Errand/Supplies,13.0
3,Fort Pierce,Fort Pierce,2016-01-05,17:31:00,2016-01-05,17:45:00,0 days 00:14:00,4.7,Business,Meeting,14.0
4,Fort Pierce,West Palm Beach,2016-01-06,14:42:00,2016-01-06,15:49:00,0 days 01:07:00,63.7,Business,Customer Visit,67.0
...,...,...,...,...,...,...,...,...,...,...,...
1151,Kar?chi,Unknown Location,2016-12-31,13:24:00,2016-12-31,13:42:00,0 days 00:18:00,3.9,Business,Temporary Site,18.0
1152,Unknown Location,Unknown Location,2016-12-31,15:03:00,2016-12-31,15:38:00,0 days 00:35:00,16.2,Business,Meeting,35.0
1153,Katunayake,Gampaha,2016-12-31,21:32:00,2016-12-31,21:50:00,0 days 00:18:00,6.4,Business,Temporary Site,18.0
1154,Gampaha,Ilukwatta,2016-12-31,22:08:00,2016-12-31,23:51:00,0 days 01:43:00,48.2,Business,Temporary Site,103.0
1155,NaN,NaN,NaT,NaT,NaT,NaT,NaT,12204.7,NaN,NaN,NaN

In [124]:
new_df.drop(1155)

,start,end,start_date,start_time,end_date,end_time,duration,miles,category,purpose,duration_minutes
0,Fort Pierce,Fort Pierce,2016-01-01,21:11:00,2016-01-01,21:17:00,0 days 00:06:00,5.1,Business,Meal/Entertain,6.0
1,Fort Pierce,Fort Pierce,2016-01-02,01:25:00,2016-01-02,01:37:00,0 days 00:12:00,5.0,Business,NaN,12.0
2,Fort Pierce,Fort Pierce,2016-01-02,20:25:00,2016-01-02,20:38:00,0 days 00:13:00,4.8,Business,Errand/Supplies,13.0
3,Fort Pierce,Fort Pierce,2016-01-05,17:31:00,2016-01-05,17:45:00,0 days 00:14:00,4.7,Business,Meeting,14.0
4,Fort Pierce,West Palm Beach,2016-01-06,14:42:00,2016-01-06,15:49:00,0 days 01:07:00,63.7,Business,Customer Visit,67.0
...,...,...,...,...,...,...,...,...,...,...,...
1150,Kar?chi,Kar?chi,2016-12-31,01:07:00,2016-12-31,01:14:00,0 days 00:07:00,0.7,Business,Meeting,7.0
1151,Kar?chi,Unknown Location,2016-12-31,13:24:00,2016-12-31,13:42:00,0 days 00:18:00,3.9,Business,Temporary Site,18.0
1152,Unknown Location,Unknown Location,2016-12-31,15:03:00,2016-12-31,15:38:00,0 days 00:35:00,16.2,Business,Meeting,35.0
1153,Katunayake,Gampaha,2016-12-31,21:32:00,2016-12-31,21:50:00,0 days 00:18:00,6.4,Business,Temporary Site,18.0
1154,Gampaha,Ilukwatta,2016-12-31,22:08:00,2016-12-31,23:51:00,0 days 01:43:00,48.2,Business,Temporary Site,103.0

In [125]:
new_df['month'] = df['start'].dt.month
new_df['day'] = df['start'].dt.day
new_df

,start,end,start_date,start_time,end_date,end_time,duration,miles,category,purpose,duration_minutes,month,day
0,Fort Pierce,Fort Pierce,2016-01-01,21:11:00,2016-01-01,21:17:00,0 days 00:06:00,5.1,Business,Meal/Entertain,6.0,1.0,1.0
1,Fort Pierce,Fort Pierce,2016-01-02,01:25:00,2016-01-02,01:37:00,0 days 00:12:00,5.0,Business,NaN,12.0,1.0,2.0
2,Fort Pierce,Fort Pierce,2016-01-02,20:25:00,2016-01-02,20:38:00,0 days 00:13:00,4.8,Business,Errand/Supplies,13.0,1.0,2.0
3,Fort Pierce,Fort Pierce,2016-01-05,17:31:00,2016-01-05,17:45:00,0 days 00:14:00,4.7,Business,Meeting,14.0,1.0,5.0
4,Fort Pierce,West Palm Beach,2016-01-06,14:42:00,2016-01-06,15:49:00,0 days 01:07:00,63.7,Business,Customer Visit,67.0,1.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1151,Kar?chi,Unknown Location,2016-12-31,13:24:00,2016-12-31,13:42:00,0 days 00:18:00,3.9,Business,Temporary Site,18.0,12.0,31.0
1152,Unknown Location,Unknown Location,2016-12-31,15:03:00,2016-12-31,15:38:00,0 days 00:35:00,16.2,Business,Meeting,35.0,12.0,31.0
1153,Katunayake,Gampaha,2016-12-31,21:32:00,2016-12-31,21:50:00,0 days 00:18:00,6.4,Business,Temporary Site,18.0,12.0,31.0
1154,Gampaha,Ilukwatta,2016-12-31,22:08:00,2016-12-31,23:51:00,0 days 01:43:00,48.2,Business,Temporary Site,103.0,12.0,31.0
1155,NaN,NaN,NaT,NaT,NaT,NaT,NaT,12204.7,NaN,NaN,NaN,NaN,NaN

In [126]:
new_df['hour_of_day'] = df['start'].dt.hour
new_df['day_of_week'] = df['start'].dt.dayofweek
new_df['day_of_week_name'] = df['start'].dt.day_name()
new_df

,start,end,start_date,start_time,end_date,end_time,duration,miles,category,purpose,duration_minutes,month,day,hour_of_day,day_of_week,day_of_week_name
0,Fort Pierce,Fort Pierce,2016-01-01,21:11:00,2016-01-01,21:17:00,0 days 00:06:00,5.1,Business,Meal/Entertain,6.0,1.0,1.0,21.0,4.0,Friday
1,Fort Pierce,Fort Pierce,2016-01-02,01:25:00,2016-01-02,01:37:00,0 days 00:12:00,5.0,Business,NaN,12.0,1.0,2.0,1.0,5.0,Saturday
2,Fort Pierce,Fort Pierce,2016-01-02,20:25:00,2016-01-02,20:38:00,0 days 00:13:00,4.8,Business,Errand/Supplies,13.0,1.0,2.0,20.0,5.0,Saturday
3,Fort Pierce,Fort Pierce,2016-01-05,17:31:00,2016-01-05,17:45:00,0 days 00:14:00,4.7,Business,Meeting,14.0,1.0,5.0,17.0,1.0,Tuesday
4,Fort Pierce,West Palm Beach,2016-01-06,14:42:00,2016-01-06,15:49:00,0 days 01:07:00,63.7,Business,Customer Visit,67.0,1.0,6.0,14.0,2.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1151,Kar?chi,Unknown Location,2016-12-31,13:24:00,2016-12-31,13:42:00,0 days 00:18:00,3.9,Business,Temporary Site,18.0,12.0,31.0,13.0,5.0,Saturday
1152,Unknown Location,Unknown Location,2016-12-31,15:03:00,2016-12-31,15:38:00,0 days 00:35:00,16.2,Business,Meeting,35.0,12.0,31.0,15.0,5.0,Saturday
1153,Katunayake,Gampaha,2016-12-31,21:32:00,2016-12-31,21:50:00,0 days 00:18:00,6.4,Business,Temporary Site,18.0,12.0,31.0,21.0,5.0,Saturday
1154,Gampaha,Ilukwatta,2016-12-31,22:08:00,2016-12-31,23:51:00,0 days 01:43:00,48.2,Business,Temporary Site,103.0,12.0,31.0,22.0,5.0,Saturday
1155,NaN,NaN,NaT,NaT,NaT,NaT,NaT,12204.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
clean_df = new_df.copy()
clean_df.drop('start_date' , axis=1, inplace=True)
clean_df.drop('end_date' , axis=1, inplace=True)
clean_df.drop('start_time' , axis=1, inplace=True)
clean_df.drop('end_time' , axis=1, inplace=True)
clean_df.drop(1155 , axis=0, inplace=True)
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1155 entries, 0 to 1154
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   start             1155 non-null   str
 1   end               1155 non-null   str
 2   duration          1155 non-null   timedelta64[us]
 3   miles             1155 non-null   float64
 4   category          1155 non-null   str
 5   purpose           653 non-null    str
 6   duration_minutes  1155 non-null   float64
 7   month             1155 non-null   float64
 8   day               1155 non-null   float64
 9   hour_of_day       1155 non-null   float64
 10  day_of_week       1155 non-null   float64
 11  day_of_week_name  1155 non-null   str
dtypes: float64(6), str(5), timedelta64[us](1)
memory usage: 108.4 KB

In [128]:
# clean_df.drop('duration_hours' , axis=1, inplace=True)

In [129]:
clean_df['day_of_week_name'] = df['start'].dt.day_name()
clean_df

,start,end,duration,miles,category,purpose,duration_minutes,month,day,hour_of_day,day_of_week,day_of_week_name
0,Fort Pierce,Fort Pierce,0 days 00:06:00,5.1,Business,Meal/Entertain,6.0,1.0,1.0,21.0,4.0,Friday
1,Fort Pierce,Fort Pierce,0 days 00:12:00,5.0,Business,NaN,12.0,1.0,2.0,1.0,5.0,Saturday
2,Fort Pierce,Fort Pierce,0 days 00:13:00,4.8,Business,Errand/Supplies,13.0,1.0,2.0,20.0,5.0,Saturday
3,Fort Pierce,Fort Pierce,0 days 00:14:00,4.7,Business,Meeting,14.0,1.0,5.0,17.0,1.0,Tuesday
4,Fort Pierce,West Palm Beach,0 days 01:07:00,63.7,Business,Customer Visit,67.0,1.0,6.0,14.0,2.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
1150,Kar?chi,Kar?chi,0 days 00:07:00,0.7,Business,Meeting,7.0,12.0,31.0,1.0,5.0,Saturday
1151,Kar?chi,Unknown Location,0 days 00:18:00,3.9,Business,Temporary Site,18.0,12.0,31.0,13.0,5.0,Saturday
1152,Unknown Location,Unknown Location,0 days 00:35:00,16.2,Business,Meeting,35.0,12.0,31.0,15.0,5.0,Saturday
1153,Katunayake,Gampaha,0 days 00:18:00,6.4,Business,Temporary Site,18.0,12.0,31.0,21.0,5.0,Saturday
1154,Gampaha,Ilukwatta,0 days 01:43:00,48.2,Business,Temporary Site,103.0,12.0,31.0,22.0,5.0,Saturday

In [130]:
clean_df['start_date'] = new_df['start_date']
clean_df['end_date'] = new_df['end_date']
clean_df

,start,end,duration,miles,category,purpose,duration_minutes,month,day,hour_of_day,day_of_week,day_of_week_name,start_date,end_date
0,Fort Pierce,Fort Pierce,0 days 00:06:00,5.1,Business,Meal/Entertain,6.0,1.0,1.0,21.0,4.0,Friday,2016-01-01,2016-01-01
1,Fort Pierce,Fort Pierce,0 days 00:12:00,5.0,Business,NaN,12.0,1.0,2.0,1.0,5.0,Saturday,2016-01-02,2016-01-02
2,Fort Pierce,Fort Pierce,0 days 00:13:00,4.8,Business,Errand/Supplies,13.0,1.0,2.0,20.0,5.0,Saturday,2016-01-02,2016-01-02
3,Fort Pierce,Fort Pierce,0 days 00:14:00,4.7,Business,Meeting,14.0,1.0,5.0,17.0,1.0,Tuesday,2016-01-05,2016-01-05
4,Fort Pierce,West Palm Beach,0 days 01:07:00,63.7,Business,Customer Visit,67.0,1.0,6.0,14.0,2.0,Wednesday,2016-01-06,2016-01-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1150,Kar?chi,Kar?chi,0 days 00:07:00,0.7,Business,Meeting,7.0,12.0,31.0,1.0,5.0,Saturday,2016-12-31,2016-12-31
1151,Kar?chi,Unknown Location,0 days 00:18:00,3.9,Business,Temporary Site,18.0,12.0,31.0,13.0,5.0,Saturday,2016-12-31,2016-12-31
1152,Unknown Location,Unknown Location,0 days 00:35:00,16.2,Business,Meeting,35.0,12.0,31.0,15.0,5.0,Saturday,2016-12-31,2016-12-31
1153,Katunayake,Gampaha,0 days 00:18:00,6.4,Business,Temporary Site,18.0,12.0,31.0,21.0,5.0,Saturday,2016-12-31,2016-12-31
1154,Gampaha,Ilukwatta,0 days 01:43:00,48.2,Business,Temporary Site,103.0,12.0,31.0,22.0,5.0,Saturday,2016-12-31,2016-12-31

In [131]:
clean_df.replace('Kar?chi', 'Karachi', inplace=True)

,start,end,duration,miles,category,purpose,duration_minutes,month,day,hour_of_day,day_of_week,day_of_week_name,start_date,end_date
0,Fort Pierce,Fort Pierce,0 days 00:06:00,5.1,Business,Meal/Entertain,6.0,1.0,1.0,21.0,4.0,Friday,2016-01-01,2016-01-01
1,Fort Pierce,Fort Pierce,0 days 00:12:00,5.0,Business,NaN,12.0,1.0,2.0,1.0,5.0,Saturday,2016-01-02,2016-01-02
2,Fort Pierce,Fort Pierce,0 days 00:13:00,4.8,Business,Errand/Supplies,13.0,1.0,2.0,20.0,5.0,Saturday,2016-01-02,2016-01-02
3,Fort Pierce,Fort Pierce,0 days 00:14:00,4.7,Business,Meeting,14.0,1.0,5.0,17.0,1.0,Tuesday,2016-01-05,2016-01-05
4,Fort Pierce,West Palm Beach,0 days 01:07:00,63.7,Business,Customer Visit,67.0,1.0,6.0,14.0,2.0,Wednesday,2016-01-06,2016-01-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1150,Karachi,Karachi,0 days 00:07:00,0.7,Business,Meeting,7.0,12.0,31.0,1.0,5.0,Saturday,2016-12-31,2016-12-31
1151,Karachi,Unknown Location,0 days 00:18:00,3.9,Business,Temporary Site,18.0,12.0,31.0,13.0,5.0,Saturday,2016-12-31,2016-12-31
1152,Unknown Location,Unknown Location,0 days 00:35:00,16.2,Business,Meeting,35.0,12.0,31.0,15.0,5.0,Saturday,2016-12-31,2016-12-31
1153,Katunayake,Gampaha,0 days 00:18:00,6.4,Business,Temporary Site,18.0,12.0,31.0,21.0,5.0,Saturday,2016-12-31,2016-12-31
1154,Gampaha,Ilukwatta,0 days 01:43:00,48.2,Business,Temporary Site,103.0,12.0,31.0,22.0,5.0,Saturday,2016-12-31,2016-12-31

In [132]:
clean_df.to_csv('cleaned_data.csv', index=False)

day2

In [4]:
import pandas as pd
clean_df = pd.read_csv('cleaned_data.csv')
clean_df['is_peak_hr'] = clean_df['hour_of_day'].isin([7,8,9,17,18,19]).astype(int)

In [7]:
clean_df['is_weekend'] = clean_df['day_of_week'].isin([5,6]).astype(int)
clean_df

,start,end,duration,miles,category,purpose,duration_minutes,month,day,hour_of_day,day_of_week,day_of_week_name,start_date,end_date,is_peak_hr,is_weekend
0,Fort Pierce,Fort Pierce,0 days 00:06:00,5.1,Business,Meal/Entertain,6.0,1.0,1.0,21.0,4.0,Friday,2016-01-01,2016-01-01,0,0
1,Fort Pierce,Fort Pierce,0 days 00:12:00,5.0,Business,NaN,12.0,1.0,2.0,1.0,5.0,Saturday,2016-01-02,2016-01-02,0,1
2,Fort Pierce,Fort Pierce,0 days 00:13:00,4.8,Business,Errand/Supplies,13.0,1.0,2.0,20.0,5.0,Saturday,2016-01-02,2016-01-02,0,1
3,Fort Pierce,Fort Pierce,0 days 00:14:00,4.7,Business,Meeting,14.0,1.0,5.0,17.0,1.0,Tuesday,2016-01-05,2016-01-05,1,0
4,Fort Pierce,West Palm Beach,0 days 01:07:00,63.7,Business,Customer Visit,67.0,1.0,6.0,14.0,2.0,Wednesday,2016-01-06,2016-01-06,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1150,Karachi,Karachi,0 days 00:07:00,0.7,Business,Meeting,7.0,12.0,31.0,1.0,5.0,Saturday,2016-12-31,2016-12-31,0,1
1151,Karachi,Unknown Location,0 days 00:18:00,3.9,Business,Temporary Site,18.0,12.0,31.0,13.0,5.0,Saturday,2016-12-31,2016-12-31,0,1
1152,Unknown Location,Unknown Location,0 days 00:35:00,16.2,Business,Meeting,35.0,12.0,31.0,15.0,5.0,Saturday,2016-12-31,2016-12-31,0,1
1153,Katunayake,Gampaha,0 days 00:18:00,6.4,Business,Temporary Site,18.0,12.0,31.0,21.0,5.0,Saturday,2016-12-31,2016-12-31,0,1
1154,Gampaha,Ilukwatta,0 days 01:43:00,48.2,Business,Temporary Site,103.0,12.0,31.0,22.0,5.0,Saturday,2016-12-31,2016-12-31,0,1

In [ ]:
clean_df.to_csv('cleaned_dataset.csv', index=False)